"""
STAGE 5 — Visual Studio Project Generator
Takes all generated C files and emits a complete, buildable VS solution.
Output: a folder you open in Visual Studio → hit Build → native .exe
"""

import os
import json
from pathlib import Path
from dataclasses import dataclass, field
from stage4_codegen import CodeGenResult, GeneratedFunction


# ── Project structure ─────────────────────────────────────────────────────────
#
#  <output_dir>/
#    <game_name>.sln
#    <game_name>.vcxproj
#    <game_name>.vcxproj.filters
#    CMakeLists.txt
#    build_vs.bat              ← double-click to generate VS project
#    src/
#      main.c                  ← entry point, frame loop
#      functions/
#        func_80001234.c       ← one file per function
#      hal/
#        n64_hal.h
#        hal_sdl.c
#    include/
#      functions.h             ← forward declarations for all functions


MAIN_C_TEMPLATE = """\
/*
 * main.c — Native Windows entry point for {game_name}
 * Auto-generated by n64recomp
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include "../include/functions.h"
#include "../hal/n64_hal.h"

/* Declared in hal_sdl.c */
extern void hal_set_rom(const uint8_t *data, size_t size);

/* First function in the recompiled binary (game binary entry) */
extern void {first_func_name}(void);

int main(int argc, char *argv[]) {{
    if (argc < 2) {{
        fprintf(stderr, "Usage: {game_name}.exe <rom.z64>\\n");
        return 1;
    }}

    /* Load ROM for PI DMA */
    FILE *f = fopen(argv[1], "rb");
    if (!f) {{ perror("fopen"); return 1; }}
    fseek(f, 0, SEEK_END);
    size_t rom_size = (size_t)ftell(f);
    rewind(f);
    uint8_t *rom_data = (uint8_t*)malloc(rom_size);
    if (!rom_data) {{ fprintf(stderr, "OOM\n"); return 1; }}
    fread(rom_data, 1, rom_size, f);
    fclose(f);
    hal_set_rom(rom_data, rom_size);

    /* Init window (320x240 default — VI will update) */
    if (!hal_init("{game_name}", 320, 240)) return 1;

    /* Boot the game */
    printf("[n64recomp] Starting {game_name}...\\n");
    {first_func_name}();

    /* Main loop (game's main loop will have jumped here via tail-call or longjmp) */
    while (hal_poll_events()) {{
        si_poll_controllers();
        hal_present();
    }}

    hal_shutdown();
    free(rom_data);
    return 0;
}}
"""

CMAKE_TEMPLATE = """\
cmake_minimum_required(VERSION 3.20)
project({game_name} C)

set(CMAKE_C_STANDARD 11)

# ── Source files ──────────────────────────────────────────────────────────────
file(GLOB FUNC_SOURCES "src/functions/*.c")

add_executable({game_name}
    src/main.c
    src/hal/hal_sdl.c
    src/hal/si.c
    ${{FUNC_SOURCES}}
)

target_include_directories({game_name} PRIVATE
    include
    src/hal
    ${{SDL2_INCLUDE_DIRS}}
)

# ── Dependencies ──────────────────────────────────────────────────────────────
# SDL2 — download from https://github.com/libsdl-org/SDL/releases
# OpenAL — download OpenAL Soft from https://github.com/kcat/openal-soft/releases
find_package(SDL2 REQUIRED)
find_package(OpenAL REQUIRED)

target_link_libraries({game_name} PRIVATE
    ${{SDL2_LIBRARIES}}
    OpenAL::OpenAL
    opengl32
)

# ── Windows-specific ─────────────────────────────────────────────────────────
if(WIN32)
    target_compile_definitions({game_name} PRIVATE _CRT_SECURE_NO_WARNINGS)
    # Static link CRT for portable .exe
    set_property(TARGET {game_name} PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded")
endif()

# ── Output ────────────────────────────────────────────────────────────────────
set_target_properties({game_name} PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY "${{CMAKE_BINARY_DIR}}/bin"
)

message(STATUS "Configured {game_name} — ${{CMAKE_BUILD_TYPE}}")
"""

BUILD_BAT_TEMPLATE = """\
@echo off
echo ============================================
echo  n64recomp — Building {game_name}
echo ============================================
echo.

REM Check for CMake
where cmake >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: CMake not found. Download from https://cmake.org
    pause
    exit /b 1
)

REM Create build directory
if not exist build mkdir build
cd build

REM Generate Visual Studio solution
cmake .. -G "Visual Studio 17 2022" -A x64 ^
    -DCMAKE_BUILD_TYPE=Release

if %ERRORLEVEL% NEQ 0 (
    echo.
    echo ERROR: CMake configure failed.
    echo Make sure SDL2 and OpenAL are installed and in your PATH.
    pause
    exit /b 1
)

echo.
echo ============================================
echo  Visual Studio project generated!
echo  Open: build\\{game_name}.sln
echo  Then: Build → Build Solution (Ctrl+Shift+B)
echo ============================================
echo.
pause
"""

SETUP_DEPS_MD = """\
# Dependencies Setup Guide

Before building `{game_name}`, install these:

## 1. Visual Studio 2022
Download: https://visualstudio.microsoft.com/
Required workloads: **Desktop development with C++**

## 2. CMake
Download: https://cmake.org/download/
✅ Check "Add CMake to system PATH" during install

## 3. SDL2
1. Download SDL2-devel-X.X.X-VC.zip from https://github.com/libsdl-org/SDL/releases
2. Extract to `C:\\libs\\SDL2`
3. Add to CMake: `-DSDL2_DIR=C:\\libs\\SDL2\\cmake`

## 4. OpenAL Soft
1. Download from https://github.com/kcat/openal-soft/releases
2. Extract to `C:\\libs\\OpenAL`
3. Add to CMake: `-DOPENAL_LIBRARY=C:\\libs\\OpenAL\\libs\\Win64\\OpenAL32.lib`

## Building
```bat
double-click build_vs.bat
```
Then open `build\\{game_name}.sln` in Visual Studio and press **Ctrl+Shift+B**.

## Running
```bat
bin\\{game_name}.exe path\\to\\your\\rom.z64
```

---
Generated by n64recomp — AI-driven N64 → Windows recompiler
"""


# ── Main generator ────────────────────────────────────────────────────────────

def generate_vs_project(cg: CodeGenResult,
                         game_name: str,
                         entry_point: int,
                         output_dir: str | Path,
                         hal_src_dir: str | Path,
                         first_func_name: str = "") -> Path:
    """
    Write all source files and project files to output_dir.
    Returns the path to the generated CMakeLists.txt.
    """
    out = Path(output_dir)
    game_slug = game_name.lower().replace(" ", "_").replace(":", "")

    # Create directory structure
    (out / "src" / "functions").mkdir(parents=True, exist_ok=True)
    (out / "src" / "hal").mkdir(parents=True, exist_ok=True)
    (out / "include").mkdir(parents=True, exist_ok=True)

    print(f"\n[STAGE 5] Generating Visual Studio project → {out}")

    # ── Write individual function .c files ────────────────────────────────────
    func_count = 0
    for gf in cg.functions:
        fname = gf.boundary.name
        c_path = out / "src" / "functions" / f"{fname}.c"
        with open(c_path, "w") as f:
            f.write(f"/* Auto-generated by n64recomp — {fname} */\n")
            f.write('#include "../../include/functions.h"\n')
            f.write('#include "../../src/hal/n64_hal.h"\n\n')
            f.write(gf.c_code)
            f.write("\n")
        func_count += 1

    print(f"  Wrote {func_count} function files")

    # ── functions.h (forward declarations) ────────────────────────────────────
    with open(out / "include" / "functions.h", "w") as f:
        f.write("/* Auto-generated forward declarations */\n")
        f.write("#pragma once\n")
        f.write('#include "../src/hal/n64_hal.h"\n\n')
        f.write("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")
        for decl in cg.header_decls:
            f.write(decl + "\n")
        f.write("\n#ifdef __cplusplus\n}\n#endif\n")

    # ── HAL files ─────────────────────────────────────────────────────────────
    import shutil
    hal_src = Path(hal_src_dir)
    for fname in ["n64_hal.h", "hal_sdl.c", "si.c"]:
        src_file = hal_src / fname
        if src_file.exists():
            dst_dir = out / "src" / "hal" if fname.endswith(".c") else out / "src" / "hal"
            shutil.copy(src_file, dst_dir / fname)
    print("  Copied HAL files")

    # ── main.c ────────────────────────────────────────────────────────────────
    with open(out / "src" / "main.c", "w") as f:
        # Use first generated function as entry, fall back to entry_point addr
        _first_func = first_func_name or (
            cg.functions[0].boundary.name if cg.functions else
            f"func_{entry_point:08x}"
        )
        f.write(MAIN_C_TEMPLATE.format(
            game_name=game_slug,
            entry_point=entry_point,
            first_func_name=_first_func,
            first_func_addr=cg.functions[0].boundary.start if cg.functions else entry_point,
        ))

    # ── CMakeLists.txt ────────────────────────────────────────────────────────
    cmake_path = out / "CMakeLists.txt"
    with open(cmake_path, "w") as f:
        f.write(CMAKE_TEMPLATE.format(game_name=game_slug))

    # ── build_vs.bat ──────────────────────────────────────────────────────────
    with open(out / "build_vs.bat", "w") as f:
        f.write(BUILD_BAT_TEMPLATE.format(game_name=game_slug))

    # ── SETUP_DEPS.md ─────────────────────────────────────────────────────────
    with open(out / "SETUP_DEPS.md", "w") as f:
        f.write(SETUP_DEPS_MD.format(game_name=game_name))

    # ── recomp_manifest.json — metadata about this build ─────────────────────
    manifest = {
        "game_name":     game_name,
        "game_slug":     game_slug,
        "entry_point":   f"0x{entry_point:08X}",
        "functions":     func_count,
        "ai_translated": sum(1 for gf in cg.functions if gf.method == "ai"),
        "deterministic": sum(1 for gf in cg.functions if gf.method == "deterministic"),
        "stubs":         sum(1 for gf in cg.functions if gf.method == "stub"),
        "warnings":      sum(len(gf.warnings) for gf in cg.functions),
    }
    with open(out / "recomp_manifest.json", "w") as f:
        json.dump(manifest, f, indent=2)

    print(f"  CMakeLists.txt written")
    print(f"  Manifest: {manifest}")
    print(f"\n  ✅ Project ready at: {out.resolve()}")
    print(f"  → Open a terminal there and run: build_vs.bat")

    return cmake_path


if __name__ == "__main__":
    print("Stage 5 project generator — run pipeline.py to use")
